// Generated by https://quicktype.io

export interface IPost {
    userId: number;
    id:     number;
    title:  string;
    body:   string;
}


// Generated by https://quicktype.io

export interface IComment {
    postId: number;
    id:     number;
    name:   string;
    email:  string;
    body:   string;
}

